### PR TITLE
Format TD to upload on the website

### PR DESCRIPTION
**Pull request by marieALaporte**
The biggest changes is that I am proposing to remove the \ from the formula. This is causing an issue when we upload the file on our website. If that is an issue, let's discuss on how to deal with the issue.

### CODE REVIEW

**Comment by BoMeyering** [comment]
Hi Marie. Yes we wrote out formulae in latex format which uses escape characters., I can go through and simplify it to a different format though

**Comment by marieALaporte** [comment]
I made the changes to the file (the one in this PR) and now it is working on our website.

**Review by BoMeyering — APPROVED** [review]

**Comment by BoMeyering** [comment]
Can I go ahead and delete this branch?

**Comment by marieALaporte** [comment]
yes, thanks.

**Pull request merged**
